# theme = "yo"

[editor]
bufferline = "multiple"
line-number = "relative"
soft-wrap.enable = true
soft-wrap.max-indent-retain=80
# mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-modification-indicator"]
center = ["file-absolute-path"]
right = ["diagnostics", "selections", "register", "position", "total-line-numbers", "position-percentage", "file-encoding"]

[editor.lsp]
enable=true
display-inlay-hints = true
auto-signature-help=true
display-messages = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[keys.normal]
C-j = "save_selection" # C-s would overwrite save-to-jumplist 
C-s = ":w" 
C-d = ":vs @gd"
S-d = "@vgld"
S-g = [":new", ":insert-output gitui", ":buffer-close!", ":redraw"]
